### ISSUE TITLE
Some environment has firestore error with createdAd timestamp problem

### ISSUE THREAD

**Issue by KishiTheMechanic** [elsoul/skeet-solana-mobile-stack#47]
```
>  Error: Error adding document: Error: Value for argument "data" is not a valid Firestore document. Couldn't serialize object of type "rme" (found in field "createdAt"). Firestore doesn't support JavaScript objects with custom prototypes (i.e. objects that were created via the "new" operator).
>      at Poa (/Users/ktm/dev/skeet-solana-mobile-stack/functions/skeet/dist/index.js:1324:711)
>      at /Users/ktm/dev/skeet-solana-mobile-stack/functions/skeet/dist/index.js:1353:1058
>      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>      at async runFunction (/Users/ktm/dev/skeet-solana-mobile-stack/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:506:9)
>      at async runHTTPS (/Users/ktm/dev/skeet-solana-mobile-stack/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:531:5)
>      at async /Users/ktm/dev/skeet-solana-mobile-stack/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:694:21
```

But other project has no error with the same method from @skeet-framework/firestore.
It's happening here so please check it.
https://github.com/elsoul/skeet-solana-mobile-stack/blob/main/functions/skeet/src/routings/http/verifySIWS.ts

**Comment by KishiTheMechanic** [comment]
It happens actually everywhere on this repository.
Seems only for this repository though, what's happening?

**Comment by KishiTheMechanic** [comment]
https://github.com/firebase/firebase-functions/issues/1496

Couldn't use firebase-admin v12.0.0 yet.
